name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: createIssueByLables
      uses: ZjBlog/create-issue-by-lables@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        filepath: issues.json
    - name: send-message
      uses: ZjBlog/message@v1.5
      env: 
        MESSAGE: "bgcz.github.io部署成功"
        URL: ${{ secrets.URL }}
      
