name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: send-message
      uses: ./test
      with:
        URL:  ${{secrets.URL}}
      env: 
        MESSAGE: "bgcz.github.io部署成功"
      
